package com.christos_bramis.bram_vortex_architecture_validator.service;

import com.christos_bramis.bram_vortex_architecture_validator.entity.AnalysisJob;
import com.christos_bramis.bram_vortex_architecture_validator.entity.ValidatorJob;
import com.christos_bramis.bram_vortex_architecture_validator.repository.AnalysisJobRepository;
import com.christos_bramis.bram_vortex_architecture_validator.repository.ValidatorJobRepository;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

@Service
public class ValidatorService {

    private final ValidatorJobRepository validatorJobRepository;
    private final AnalysisJobRepository analysisJobRepository;
    private final ChatModel chatModel;
    private final ObjectMapper objectMapper;

    public ValidatorService(ValidatorJobRepository validatorJobRepository,
                            AnalysisJobRepository analysisJobRepository,
                            ChatModel chatModel) {
        this.validatorJobRepository = validatorJobRepository;
        this.analysisJobRepository = analysisJobRepository;
        this.chatModel = chatModel;
        this.objectMapper = new ObjectMapper();
    }

    public void startArchitectureValidation(String validatorJobId, String analysisJobId, String userId, String token) {
        System.out.println("\n🚀 [VORTEX-VALIDATOR] Starting Validation for Job: " + validatorJobId);

        ValidatorJob job = new ValidatorJob();
        job.setId(validatorJobId);
        job.setAnalysisJobId(analysisJobId);
        job.setUserId(userId);
        job.setStatus("GENERATING");
        validatorJobRepository.save(job);

        CompletableFuture.runAsync(() -> {
            try {
                // 1. Fetching Blueprint and RAW Master ZIP from AnalysisJob
                System.out.println("🔍 [VALIDATOR] Fetching Blueprint and RAW Master ZIP...");
                AnalysisJob analysisJob = analysisJobRepository.findById(analysisJobId)
                        .orElseThrow(() -> new RuntimeException("Analysis blueprint not found"));

                String blueprintJson = analysisJob.getBlueprintJson() != null ?
                        analysisJob.getBlueprintJson() : "{}";

                byte[] rawMasterZip = analysisJob.getMasterZip();
                if (rawMasterZip == null || rawMasterZip.length == 0) {
                    throw new RuntimeException("RAW Master ZIP is missing from Analysis Job!");
                }

                // 2. Unzipping the RAW ZIP into a Map
                Map<String, String> rawFiles = new HashMap<>();
                extractZipToMap(rawMasterZip, rawFiles);

                if (rawFiles.isEmpty()) {
                    throw new RuntimeException("No files were extracted from the RAW Master ZIP. Validation aborted.");
                }

                // 3. Convert files to JSON String for the AI Prompt
                String filesJsonString = objectMapper.writeValueAsString(rawFiles);

                // 4. AI Dispatch - THE VALIDATOR PROMPT
                String prompt = String.format("""
                    You are a Principal Cloud Architect and Cross-Service Validator.
                    Your objective is to validate, debug, and unify the generated Infrastructure (Terraform), Configuration (Ansible), and Pipeline (GitHub Actions) files.

                    --- ARCHITECTURAL BLUEPRINT (JSON) ---
                    %s
                    --------------------------------------

                    --- GENERATED FILES CURRENT STATE (JSON) ---
                    %s
                    --------------------------------------------

                    VALIDATION REQUIREMENTS (CRITICAL):
                    1. **Cross-Reference Check**: Ensure that ports, usernames, and database credentials match perfectly across Terraform, Ansible, and the GitHub Action.
                    2. **Dependencies**: Ensure the GitHub Action pipeline expects the exact infrastructure generated by Terraform.
                    3. **Syntax & Completeness**: Fix any missing variables, broken YAML spacing, or incomplete Terraform blocks.
                    4. **Do NOT delete files**: You must return ALL the files provided in the 'GENERATED FILES' section, including the ones you did not modify.
                    5. **PRESERVE DIRECTORY STRUCTURE (CRITICAL)**: You MUST use the EXACT SAME keys (file paths) provided in the 'GENERATED FILES CURRENT STATE' JSON. Do not rename files or remove the 'infrastructure/' or 'configuration/' folder prefixes.
                    6. **SECRET MANAGEMENT (CRITICAL)**: DO NOT hardcode any passwords, API keys, or tokens. Actual credentials will be injected dynamically by the Execution Service later.
                       - For Terraform (.tf): Use variables (e.g., `var.db_password`). Ensure these variables are properly declared in an `infrastructure/variables.tf` file without sensitive default values. Create it if it doesn't exist.
                       - For Ansible (.yml): Use environment variable lookups (e.g., `"{{ lookup('env', 'DB_PASSWORD') }}"`).
                       - For GitHub Actions (.yml): Use GitHub Secrets (e.g., `${{ secrets.DB_PASSWORD }}`).

                    OUTPUT FORMAT (CRITICAL):
                        - Respond ONLY with a SINGLE, VALID JSON object containing ALL the final, validated files.
                        - NO markdown blocks (e.g., no ```json).
                        - NO conversational text.

                    EXPECTED JSON SCHEMA:
                    {
                        "infrastructure/main.tf": "<validated content>",
                        "infrastructure/variables.tf": "<validated content>",
                        "configuration/playbook.yml": "<validated content>",
                        ".github/workflows/deploy.yml": "<validated content>",
                        "...": "..."
                    }
                    """, blueprintJson, filesJsonString);

                System.out.println("🧠 [VALIDATOR] Calling AI for Cross-Reference Check...");
                String aiResponse = chatModel.call(prompt);

                // 5. Robust Parsing
                Map<String, String> validatedFiles = parseResponse(aiResponse);

                if (validatedFiles == null || validatedFiles.isEmpty()) {
                    throw new RuntimeException("AI returned empty file set or invalid JSON format");
                }

                // 6. Zipping to VALIDATED MASTER ZIP
                System.out.println("🤐 [VALIDATOR] Creating VALIDATED MASTER ZIP for " + validatedFiles.size() + " files...");
                byte[] finalMasterZipBytes = createZipInMemory(validatedFiles);

                if (finalMasterZipBytes == null || finalMasterZipBytes.length < 100) {
                    throw new RuntimeException("Generated VALIDATED MASTER ZIP is suspiciously small.");
                }

                // 7. Finalize
                job.setMasterZip(finalMasterZipBytes);
                job.setStatus("COMPLETED");
                validatorJobRepository.save(job);
                notifyOrchestrator(analysisJobId, "VALIDATOR", "COMPLETED", token);
                System.out.println("✅ [VALIDATOR] Success! VALIDATED MASTER ZIP size: " + finalMasterZipBytes.length + " bytes.");

            } catch (Exception e) {
                System.err.println("❌ [VALIDATOR ERROR]: " + e.getMessage());
                job.setStatus("FAILED");
                validatorJobRepository.save(job);
                notifyOrchestrator(analysisJobId, "VALIDATOR", "FAILED", token);
            }
        });
    }

    private void extractZipToMap(byte[] zipBytes, Map<String, String> combinedFiles) throws Exception {
        if (zipBytes == null || zipBytes.length == 0) return;

        try (ZipInputStream zis = new ZipInputStream(new ByteArrayInputStream(zipBytes))) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                if (!entry.isDirectory()) {
                    ByteArrayOutputStream buffer = new ByteArrayOutputStream();
                    zis.transferTo(buffer);
                    // Το entry.getName() εδώ περιέχει ολόκληρο το path (π.χ. "infrastructure/main.tf")
                    combinedFiles.put(entry.getName(), buffer.toString(StandardCharsets.UTF_8));
                }
            }
        }
    }

    private void notifyOrchestrator(String jobId, String service, String status, String token) {
        String url = String.format("http://repo-analyzer-svc/dashboard/internal/callback/%s?service=%s&status=%s",
                jobId, service, status);

        RestClient internalClient = RestClient.create();
        internalClient.post()
                .uri(url)
                .header("Authorization", "Bearer " + token)
                .retrieve()
                .toBodilessEntity();
    }

    private Map<String, String> parseResponse(String response) {
        if (response == null || response.trim().isEmpty()) {
            System.err.println("⚠️ [PARSING ERROR] AI response is null or empty");
            return new HashMap<>();
        }
        try {
            String clean = response.trim();
            if (clean.startsWith("```")) {
                clean = clean.replaceAll("^```json\\s*", "").replaceAll("```$", "").trim();
            }
            return objectMapper.readValue(clean, new TypeReference<HashMap<String, String>>() {});
        } catch (Exception e) {
            System.err.println("⚠️ [PARSING ERROR] Failed to convert AI response to Map: " + e.getMessage());
            return new HashMap<>();
        }
    }

    private byte[] createZipInMemory(Map<String, String> files) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(baos)) {
            for (Map.Entry<String, String> entry : files.entrySet()) {
                if (entry.getValue() == null || entry.getValue().isEmpty()) continue;

                System.out.println("   [+] Packing validated file into ZIP: " + entry.getKey());

                // Όταν δίνουμε στη ZipEntry το κλειδί "infrastructure/main.tf",
                // δημιουργεί αυτόματα τους φακέλους μέσα στο αρχείο ZIP!
                ZipEntry zipEntry = new ZipEntry(entry.getKey());
                zos.putNextEntry(zipEntry);
                zos.write(entry.getValue().getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();
            }
            zos.finish();
            zos.flush();
        }
        return baos.toByteArray();
    }
}